In [1]:
import re
import requests
import pandas as pd

In [2]:
ud = "https://raw.githubusercontent.com/UniversalDependencies/UD_Yakut-YKTDT/dev/sah_yktdt-ud-test.conllu"
f = requests.get(ud)
file = f.text.split("\n")
#file

In [3]:
rege = r"^\d+\t"
lst = []

for line in file:
    if re.match(rege, line):
        #print(line)
        lst.append(line)

In [4]:
df = pd.DataFrame([sub.split("\t") for sub in lst])
colnames = ["ID", "WORD", "LEMMA", "POS", "SPOS", "FEATURES", "6", "7", "8", "9"]
df.columns = colnames

In [5]:
df1 = df.drop(["ID", "SPOS", "6", "7", "8", "9", ], axis=1)
df1['WORD'] = df1['WORD'].str.lower()
df1['LEMMA'] = df1['LEMMA'].str.lower()

In [6]:
df1.head(25)

,WORD,LEMMA,POS,FEATURES
0,кинилэр,кини,PRON,Case=Nom|Number=Plur|Person=3|PronType=Prs
1,кэллилэр,кэл,VERB,Number=Plur|Person=3|Tense=NearPast
2,кинигэлэри,кинигэ,NOUN,Case=Acc|Number=Plur
3,күн,күн,NOUN,Case=Nom|Number=Sing
4,аайы,аайы,DET,_
5,ааҕабын,аах,VERB,Number=Sing|Person=1|Tense=Pres
6,илиибин,илии,NOUN,Case=Acc|Number=Sing|Number[psor]=Sing|Person[...
7,сууннум,сууй,VERB,Number=Sing|Person=1|Tense=NearPast
8,биһиги,биһиги,PRON,Case=Nom|Number=Plur|Person=1|PronType=Prs
9,манна,манна,ADV,_
10,баарбыт,баар,AUX,Number=Plur|Person=1|Tense=Pres
11,эн,эн,PRON,Case=Nom|Number=Sing|Person=2|PronType=Prs
12,профессор,профессор,NOUN,Case=Nom|Number=Sing
13,буолуоҥ,буол,VERB,Number=Sing|Person=2|Tense=Fut
14,манна,манна,ADV,_
15,остуол,остуол,NOUN,Case=Nom|Number=Sing
16,",",",",PUNCT,_
17,олоппос,олоппос,NOUN,Case=Nom|Number=Sing
18,",",",",PUNCT,_
19,ыскамыайка,ыскамыайка,NOUN,Case=Nom|Number=Sing
20,баар,баар,AUX,_
21,кылааска,кылаас,NOUN,Case=Dat|Number=Sing
22,элбэх,элбэх,ADJ,_
23,паарта,паарта,NOUN,Case=Nom|Number=Sing
24,турар,тур,VERB,Number=Sing|Person=3|Tense=Pres

In [7]:
df1 = df1[~df1["LEMMA"].str.contains("_")]
df1
df1.sort_values(by=['POS'])

             WORD    LEMMA   POS                                FEATURES
345    ынырыктаах   ынырык   ADJ                                Poss=Yes
1446      дьэҥкир  дьэҥкир   ADJ                                       _
1044         эдэр     эдэр   ADJ                                       _
1028       улахан   улахан   ADJ                                       _
1463        элбэх    элбэх   ADJ                                       _
...           ...      ...   ...                                     ...
1260  кэрдиэхтэрэ      кэр  VERB          Number=Plur|Person=3|Tense=Fut
1256     уураллар      уур  VERB         Number=Plur|Person=3|Tense=Pres
319       оргуйар    оргуй  VERB         Number=Sing|Person=3|Tense=Pres
1295   үөрэнэллэр    үөрэн  VERB         Number=Plur|Person=3|Tense=Pres
357     ыйыстыбыт   ыйыһын  VERB  Number=Sing|Person=3|Tense=PastResultI

[1740 rows x 4 columns]

In [8]:
pos = sorted(df1["POS"].unique())
pos

['ADJ',
 'ADP',
 'ADV',
 'AUX',
 'CCONJ',
 'DET',
 'INTJ',
 'NOUN',
 'NUM',
 'PART',
 'PRON',
 'PROPN',
 'PUNCT',
 'VERB']

In [9]:
with open ("lexicon_ud.txt", "a", encoding="utf-8") as w:
    
    w.write("LEXICON Root" + "\n")
    for p in pos:
        w.write("\t" + p + ";" + "\n")
    w.write("\n\n")

    for p in pos:
        w.write("\n")
        w.write("LEXICON " + p + "\n")
        for i in df1[df1["POS"].str.contains(p)].LEMMA.unique():
            w.write(i + "\t" + p.lower() + "first;" + "\n")
        w.write("\n\n")
        w.write("LEXICON " + p.lower() + "first" + "\n")
        w.write("\t" + "#;" + "\n")
        w.write("\n\n")

In [10]:
#df_noun = df1[df1["POS"].str.contains("NOUN")]
#df2 = df1.sort_values(by=['POS']).drop_duplicates()
#df2

In [11]:
#alls = df2.groupby('POS').count()
#alls

In [12]:
#df_noun = df1[df1["POS"].str.contains("NOUN")]
df2 = df1.sort_values(by=['POS']).drop_duplicates()
df2

             WORD    LEMMA   POS                                FEATURES
345    ынырыктаах   ынырык   ADJ                                Poss=Yes
1446      дьэҥкир  дьэҥкир   ADJ                                       _
1044         эдэр     эдэр   ADJ                                       _
1028       улахан   улахан   ADJ                                       _
1463        элбэх    элбэх   ADJ                                       _
...           ...      ...   ...                                     ...
1264     маныаҕыҥ    манаа  VERB          Number=Sing|Person=2|Tense=Fut
1260  кэрдиэхтэрэ      кэр  VERB          Number=Plur|Person=3|Tense=Fut
1256     уураллар      уур  VERB         Number=Plur|Person=3|Tense=Pres
319       оргуйар    оргуй  VERB         Number=Sing|Person=3|Tense=Pres
357     ыйыстыбыт   ыйыһын  VERB  Number=Sing|Person=3|Tense=PastResultI

[676 rows x 4 columns]

In [13]:
df_noun = df2[df2["POS"].str.contains("VERB")]
len(df_noun["LEMMA"].unique())

83

In [14]:
from collections import Counter
Counter(df2["POS"]).most_common()

[('NOUN', 317),
 ('VERB', 194),
 ('ADV', 46),
 ('ADJ', 36),
 ('PRON', 31),
 ('PROPN', 16),
 ('NUM', 10),
 ('INTJ', 6),
 ('PUNCT', 6),
 ('AUX', 4),
 ('PART', 4),
 ('DET', 3),
 ('CCONJ', 2),
 ('ADP', 1)]

In [15]:
df2["POS"] = df2["POS"] + "|" + df2["FEATURES"] 
df2["POS"] = df2["POS"].str.replace("|_", "", regex=False)
df2["POS"]

345                                    ADJ|Poss=Yes
1446                                            ADJ
1044                                            ADJ
1028                                            ADJ
1463                                            ADJ
                           ...
1264            VERB|Number=Sing|Person=2|Tense=Fut
1260            VERB|Number=Plur|Person=3|Tense=Fut
1256           VERB|Number=Plur|Person=3|Tense=Pres
319            VERB|Number=Sing|Person=3|Tense=Pres
357     VERB|Number=Sing|Person=3|Tense=PastResultI
Name: POS, Length: 676, dtype: object

In [16]:
df2["POS"] = df2["POS"].str.replace("|", ">|<")

/var/folders/2p/6pqnd6yj0zx2p_7m_3ntmldm0000gn/T/ipykernel_11582/1621994939.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2["POS"] = df2["POS"].str.replace("|", ">|<")

In [17]:
df2["POS"] = df2["POS"].str.replace(r"(^)", "<", regex=True)
df2["POS"] = df2["POS"].str.replace(r"($)", ">", regex=True)

In [18]:
df2

,WORD,LEMMA,POS,FEATURES
345,ынырыктаах,ынырык,<ADJ>|<Poss=Yes>,Poss=Yes
1446,дьэҥкир,дьэҥкир,<ADJ>,_
1044,эдэр,эдэр,<ADJ>,_
1028,улахан,улахан,<ADJ>,_
1463,элбэх,элбэх,<ADJ>,_
...,...,...,...,...
1264,маныаҕыҥ,манаа,<VERB>|<Number=Sing>|<Person=2>|<Tense=Fut>,Number=Sing|Person=2|Tense=Fut
1260,кэрдиэхтэрэ,кэр,<VERB>|<Number=Plur>|<Person=3>|<Tense=Fut>,Number=Plur|Person=3|Tense=Fut
1256,уураллар,уур,<VERB>|<Number=Plur>|<Person=3>|<Tense=Pres>,Number=Plur|Person=3|Tense=Pres
319,оргуйар,оргуй,<VERB>|<Number=Sing>|<Person=3>|<Tense=Pres>,Number=Sing|Person=3|Tense=Pres
357,ыйыстыбыт,ыйыһын,<VERB>|<Number=Sing>|<Person=3>|<Tense=PastRes...,Number=Sing|Person=3|Tense=PastResultI

In [19]:
#df_noun["POS"]
#df2['POS'] = (df2['POS'].add(';')
#             .str.replace(r'(.*)(NOUN)(.*)(.*)(Number=(Plur|Sing))', r'\1\2\4\6\3', regex=True)
#             .str.strip(';'))

In [20]:
df2 = df2.drop("FEATURES", axis=1)

In [21]:
df2 = df2.sort_values(by=['POS'])#.head(10)
df2

           WORD      LEMMA                                           POS
822   халтархай  халтархай                                         <ADJ>
1427       хара       хара                                         <ADJ>
466        эмис       эмис                                         <ADJ>
314       алтан      алтан                                         <ADJ>
1230    куһаҕан    куһаҕан                                         <ADJ>
...         ...        ...                                           ...
987         ыыр         ыа  <VERB>|<Number=Sing>|<Person=3>|<Tense=Pres>
1718      аһыыр       аһаа  <VERB>|<Number=Sing>|<Person=3>|<Tense=Pres>
1722      үүнэр        үүн  <VERB>|<Number=Sing>|<Person=3>|<Tense=Pres>
353        күлэ        күл          <VERB>|<Tense=Pres>|<VerbForm=Trans>
445        үүнэ        үүн          <VERB>|<Tense=Pres>|<VerbForm=Trans>

[676 rows x 3 columns]

In [22]:
df2 = df2[["LEMMA", "WORD", "POS"]]

In [23]:
#test = df2[df2["POS"].str.contains("VERB")]

In [33]:
len(df2.LEMMA.unique())

427

In [34]:
len(df2.POS.unique())

101

In [25]:
df2#.LEMM.unique()

          LEMMA       WORD                                           POS
822   халтархай  халтархай                                         <ADJ>
1427       хара       хара                                         <ADJ>
466        эмис       эмис                                         <ADJ>
314       алтан      алтан                                         <ADJ>
1230    куһаҕан    куһаҕан                                         <ADJ>
...         ...        ...                                           ...
987          ыа        ыыр  <VERB>|<Number=Sing>|<Person=3>|<Tense=Pres>
1718       аһаа      аһыыр  <VERB>|<Number=Sing>|<Person=3>|<Tense=Pres>
1722        үүн      үүнэр  <VERB>|<Number=Sing>|<Person=3>|<Tense=Pres>
353         күл       күлэ          <VERB>|<Tense=Pres>|<VerbForm=Trans>
445         үүн       үүнэ          <VERB>|<Tense=Pres>|<VerbForm=Trans>

[676 rows x 3 columns]

In [26]:
nouns = ["NOUN", "PROPN", "NUM", "PRON", "DET"]

In [27]:
df_nouns = df2[df2["POS"].str.contains('|'.join(nouns))]
df_verbs = df2[~df2["POS"].str.contains('|'.join(nouns))]

In [28]:
import re
df_nouns.head()

        LEMMA         WORD                              POS
1079       бу           бу                            <DET>
4        аайы         аайы                            <DET>
454        бу         маны                 <DET>|<Case=Acc>
1120   яблоко   яблокаттан  <NOUN>|<Case=Abl>|<Number=Sing>
164   оскуола  оскуолаттан  <NOUN>|<Case=Abl>|<Number=Sing>

In [29]:
df_nouns['POS'] = (df_nouns['POS']#.add('|')
            .str.replace(r'(<NOUN>)(\|)(.+)(\|)(<Number=.*)', r'\1\5\3', regex=True)
              )

/var/folders/2p/6pqnd6yj0zx2p_7m_3ntmldm0000gn/T/ipykernel_11582/2240970813.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nouns['POS'] = (df_nouns['POS']#.add('|')

In [30]:
df_nouns['POS'] = df_nouns['POS'].str.replace("><", ">|<")

/var/folders/2p/6pqnd6yj0zx2p_7m_3ntmldm0000gn/T/ipykernel_11582/609591294.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nouns['POS'] = df_nouns['POS'].str.replace("><", ">|<")

In [31]:
df_nouns

           LEMMA          WORD                              POS
1079          бу            бу                            <DET>
4           аайы          аайы                            <DET>
454           бу          маны                 <DET>|<Case=Acc>
1120      яблоко    яблокаттан  <NOUN>|<Number=Sing>|<Case=Abl>
164      оскуола   оскуолаттан  <NOUN>|<Number=Sing>|<Case=Abl>
...          ...           ...                              ...
145       петров      петровка               <PROPN>|<Case=Dat>
148   дьокуускай  дьокуускайга               <PROPN>|<Case=Dat>
1165       айхал       айхалга               <PROPN>|<Case=Dat>
248       кэскил      кэскилга               <PROPN>|<Case=Dat>
919        айтал       айталга               <PROPN>|<Case=Dat>

[377 rows x 3 columns]

In [32]:
df_nouns.to_csv("sah_nouns.dev", sep="\t", encoding="utf-8", index = False)
df_verbs.to_csv("sah_verbs.dev", sep="\t", encoding="utf-8", index = False)